"""add Author.hobby

Revision ID: dd3b966750c9
Revises: 
Create Date: 2021-12-12 23:16:21.644713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd3b966750c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('hobby', sa.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'hobby')
    # ### end Alembic commands ###
